jannate.rahim
KushGandhi3/Forecastly pull request #25
Opened 2024-11-21 03:27 UTC by jannate-r

2024-11-22 02:07 UTC, Kurochiisu submitted a review, later dismissed

2024-11-22 02:07 UTC, Kurochiisu commented on src/main/java/view/HomeView.java
listeners and actions can be combined. I think you can also introduce a single method for updating the labels to improve readability.

2024-11-22 22:20 UTC, daniilio requested changes
Please fix remove the boolean variables for the buttons in DisplayHomeInputData as Chika requested. Please also remove any mention of WeatherDataFactory from the DisplayHomeInteractor. It shouldn't be using a WeatherDataFactory.

2024-11-22 22:20 UTC, daniilio commented on src/main/java/use_case/display_home/DisplayHomeInputData.java
Yep, this still needs to be fixed Jannate. Please push your changes when you are done.

2024-11-23 16:21 UTC, daniilio approved these changes
Looks good.

2024-11-23 16:40 UTC, merged