Updated Hourly Use Case
KushGandhi3/Forecastly pull request #35
Opened 2024-11-25 10:26 UTC by dakhmedova30

I updated the files for my use case.

2024-11-25 14:28 UTC, daniilio requested changes
Your implementation isn't looking quite correct, look at the entities and make sure your implementation matches the available data there. Also refer to the figma to make sure you're displaying the correct data. For example, notice that for the detailed weather data, you will only be displaying it for one hour at a time! Also please note that each hour is a button, and hence the detailed view will change depending on which hour the user selects.

2024-11-25 15:51 UTC, dakhmedova30 commented
I updated some of the files, what else would you suggest changing?

2024-11-25 23:37 UTC, daniilio requested changes
Please implement the changes I have requested. I think you must of forgot to modify some of the files. Also, please use javadocs to describe all of your classes.

2024-11-25 23:37 UTC, daniilio commented on src/main/java/interface_adapter/display_hourly/DisplayHourlyState.java
You will need an array of times for each hour of the weather forecast. We also aren't doing air quality anymore, the figma and entities both replaced air quality with cloudCover, please update that accordingly. Since this is only the state of the view, you shouldn't be including extra data that won't be displayed. Only one of the uvIndex, feelsLike, windSpeed, cloudCover, humidity, precipitation should be available (as in they should be variables like "int" or "String" not arrays) (other variables like time and condition do need to stay as arrays because we're displaying the full array of data in the view!).

2024-11-25 23:37 UTC, daniilio commented on src/main/java/use_case/display_hourly/DisplayHourlyInputBoundary.java
You should be inputting the DisplayHourlyInputData, not DisplayHourlyInputBoundary. The input boundary is an interface for the interactor. Also, you need to include a method, "void switchToHomeView();"

2024-11-25 23:37 UTC, daniilio commented on src/main/java/interface_adapter/display_hourly/DisplayHourlyPresenter.java
Make sure this class implements DisplayHourlyOutputBoundary.

2024-11-25 23:37 UTC, daniilio commented on src/main/java/use_case/display_hourly/DisplayHourlyOutputData.java
Make sure time is an array, since there are an array of times. Also you used airQuality again in the constructor

2024-11-29 14:10 UTC, dakhmedova30 commented on src/main/java/use_case/display_hourly/DisplayHourlyOutputData.java
I updated all of the files, they should work correctly now, but let me know if there is anything I should change!

2024-12-01 04:22 UTC, closed without merging